### ISSUE TITLE
v0.11 renders page content only 24 characters wide.

### ISSUE THREAD

**Issue by verkaro** [hedyhli/gelim#6]
I used the prebuilt binary. The page rendering has changed. This is a snippet from my spartan site:
                                                                   # Beanstitch.net

                                                                   Hello, my name is
                                                                   Warren Smith. Currently
                                                                   I’m building a mobile
                                                                   recording kit to give
                                                                   audiobook production
                                                                   another shot. Some time

**Comment by hedyhli** [comment]
hmm, this shouldn't be happening. I went to have a look and I am getting this:
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/32bf5380-4034-4337-aca8-c34b3e31e9f2" />

Tested with the latest prebuilt binary for linux x86-64.

Maybe it's caused by your `~/.config/gelim/config.toml` (specifically `maxWidth`?)

**Comment by verkaro** [comment]
hmm. yeah, I just tried the latest prebuilt on my Chromebook and it worked fine there. Tomorrow I'll login on the machine I had trouble with.

**Comment by verkaro** [comment]
on my wyse 5070 I can confirm that v.011 w/o a gelim config displays in error 24 characters wide. But downloading v0.13.1 and running on this same box w/o a config now works as expected. Thanks.

**Comment by hedyhli** [comment]
Oh I see. Alright then!
